/**
 * 歌曲名称到ID的映射表
 * 用于将用户选择的歌曲名称映射到物量数据库中的ID
 */

// 由于完整映射表很大，这里只列出部分示例，实际使用时需要导入完整数据
export const songIdMap: Record<string, string> = {
  "Testify": "testify",
  "Designant.": "designant",
  "Tempestissimo": "tempestissimo",
  "Arcana Eden": "arcanaeden",
  "Pentiment": "pentiment",
  "Sayonara Hatsukoi": "sayonarahatsukoi",
  "Lost Civilization": "lostcivilization",
  "goodtek": "goodtek",
  "Viyella's Tears": "viyella",
  "Rise": "rise",
  "Lucifer": "lucifer",
  "Fairytale": "fairytale",
  "Corruption": "corruption",
  "GIRLPOWER!: GL": "girlband",
  "Modelista": "modelista",
  "ANTITHESE": "antithese",
  "SHADES OF LIGHT IN A SEA OF DARKNESS": "shadesoflight",
  "Fracture Ray": "fractureray",
  "World Ender": "worldender",
  "Grievous Lady": "grievouslady",
  "Constellation of Hope": "constellation",
  "Cyaegha": "cyaegha",
  "SIN": "sin",
  "PRAGMATISM": "pragmatism",
  "Ether Strike": "etherstrike",
  "Harutopia": "harutopia",
  "Asher": "asher",
  "Ringed Genesis": "ringedgenesis",
  "DIVE": "dive",
  "Empire of Winter": "empireofwinter",
  "Sheriruth": "sheriruth",
  "Collapsed Superstar": "collapsedsuperstar",
  "Anökumene": "anokumene",
  "Lost Song": "lostsong",
  "Seventh Sense": "seventhsense",
  "Monochrome Princess": "monochromeprincess",
  "Alea Jacta Est": "aleajactaest",
  "SFUMATE": "sfumagate",
  "Parallel Lines": "parallelline",
  "Essence of Twilight": "essenceoftwilight",
  "Black Lotus": "blacklotus",
  "Cyclone": "cyclone",
  "Odelia": "odelia",
  "Ignotus": "ignotus",
  "Glory Road": "gloryroad",
  "Qualia": "qualia",
  "Suomi": "suomi",
  "Cotopaxi": "cotopaxi",
  "Diode": "diode",
  "Third Anxiety": "thirdanxiety",
  "Vexaria": "vexaria",
  "Freedom Dive": "freedombive",
  "Mirzam": "mirzam",
  "Depressed": "depressed",
  "Chronostasis": "chronostasis",
  "Heaven's Door": "heavensdoor",
  "Moonheart": "moonheart",
  // 更多歌曲映射...
}